import { readFileSync, writeFileSync } from 'node:fs';
// Generated by scripts/export-mofu-v2.mjs after `forge build` in ../contracts.
for (const [contract, name] of [['MofuFactoryV2', 'mofuFactoryV2'], ['MofuTokenV2', 'mofuTokenV2'], ['MofuPool', 'mofuPool']]) {
  const artifact = JSON.parse(readFileSync(new URL(`../../contracts/out/MofuV2.sol/${contract}.json`, import.meta.url)));
  writeFileSync(new URL(`../app/generated/${name}.ts`, import.meta.url), `// Generated by scripts/export-mofu-v2.mjs after forge build.\nexport const ${name} = ${JSON.stringify({ abi: artifact.abi, bytecode: artifact.bytecode.object }, null, 2)} as const;\n`);
}
console.log('Exported mofuFactoryV2, mofuTokenV2, mofuPool');
