import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const artifact = JSON.parse(readFileSync(new URL('../../contracts/out/LaunchToken.sol/LaunchToken.json', import.meta.url)));
mkdirSync(new URL('../app/generated/', import.meta.url), { recursive: true });
writeFileSync(new URL('../app/generated/launch-token.ts', import.meta.url), `// Generated by scripts/export-token.mjs after forge build.\nexport const launchToken = ${JSON.stringify({ abi: artifact.abi, bytecode: artifact.bytecode.object }, null, 2)} as const;\n`);
