import { readFileSync, writeFileSync } from 'node:fs';
for (const [contract, name] of [['CurveToken', 'curveToken'], ['CurveLaunchpad', 'curveLaunchpad']]) {
  const artifact = JSON.parse(readFileSync(new URL(`../../contracts/out/CurveLaunchpad.sol/${contract}.json`, import.meta.url)));
  writeFileSync(new URL(`../app/generated/${name}.ts`, import.meta.url), `// Generated by scripts/export-curves.mjs after forge build.\nexport const ${name} = ${JSON.stringify({ abi: artifact.abi, bytecode: artifact.bytecode.object }, null, 2)} as const;\n`);
}
